version: '3'
services:
  mongodb:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
      - "27018:27087"
      - "27019:27019"
